---
- name: "Install Red Hat OpenShift AI bundle on OpenShift"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='feature/rhoai/') }}"
    validate_certs: false
