---
- name: Install Operators
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='feature/operators/') }}"
    validate_certs: false

- name: Wait for NVIDIA GPU Operator to be ready
  kubernetes.core.k8s_info:
    namespace: nvidia-gpu-operator
    kind: Pod
    label_selectors:
      - app=gpu-operator
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: 'True'

- name: Apply NVIDIA GPU Clusterpolicy
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='feature/nvidia/') }}"
    validate_certs: false

- name: Wait for RHOAI operator to be ready
  kubernetes.core.k8s_info:
    namespace: redhat-ods-operator
    kind: Pod
    label_selectors:
      - name=rhods-operator
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: 'True'

- name: Apply RHOAI CRDs
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='feature/rhoai/') }}"
    validate_certs: false

- name: Apply NFD instance
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='feature/nfd/') }}"
    validate_certs: false

- name: Wait for NVIDIA GPU Feature Discovery to be Ready
  kubernetes.core.k8s_info:
    namespace: nvidia-gpu-operator
    kind: Pod
    label_selectors:
      - app=gpu-feature-discovery
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: 'True'

- name: Deploy Minio S3 Storage
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='feature/minio/') }}"
    validate_certs: false

- name: Wait for Minio Jobs to Finish
  kubernetes.core.k8s_info:
    namespace: demo
    kind: Job
    name: create-minio-buckets
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Complete
      status: "True"

- name: Upload Granite Model
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='feature/upload-model/') }}"
    validate_certs: false

- name: Wait for Granite Model to Finish Uploading
  kubernetes.core.k8s_info:
    namespace: demo
    kind: Job
    name: upload-granite-model
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Complete
      status: "True"

- name: Deploy Granite Model and vLLM ServingRuntime
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='feature/models/') }}"
    validate_certs: false

- name: Deploy llm-load-test-exporter
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='feature/llm-load-test-exporter/') }}"
    validate_certs: false
