apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      bundle: nfd
    includeSelectors: true
resources:
  - ../../base/core/namespaces/nvidia-gpu-operator
  - ../../base/operators.coreos.com/operatorgroups/nvidia-gpu-operator
  - ../../base/operators.coreos.com/subscriptions/nvidia-gpu-operator
